version: "3.9"
services:
# PRODUCTION SERVICES
  flask-nginx-server:
    build: docker/jupyter-0.0
    network_mode: host
    ports: 
      - 3398:3389
      - 80:80
    volumes:
      - ${HOME}:/home/jovyan/work
    command: bash -c "jupyter notebook -port 3389"

